### ISSUE TITLE
S+T pressed anywhere in game doesn't do anything

### ISSUE THREAD

**Issue by geewhizbang** [NyokoDev/STCC#1]
I used the Thunderstore Mod Manager to load this, I have not found any way to load the checker in the game. I'm not sure what you even mean about "Main Menu" I've tried it in game, and in the menu where you start a new game.

Sorry about complaining here, I haven't found anywhere else to ask.

**Comment by NyokoDev** [comment]
Hello! That functionality is long gone and this mod has been outdated for a while! You can still use it to export your logs and such by navigating to the application's directory.

In this case, that directory would be: YourRoamingLocation\BepInEx\plugins\Nyoko-STCC_ShortTermCompatibilityChecker

To easily navigate and find the app use r2modman's or your mod manager's option "Browse profile folder"
